app/main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-


from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import Required


class SearchForm(FlaskForm):
    searchName = StringField(u'搜索', validators=[Required()])
    submit = SubmitField(u'搜索')

app/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from . import main
from .. import cache
from ..utils import feeds
from .forms import SearchForm
from ..models import User, Category, Tag, Post, Type
from flask import render_template, redirect, url_for, abort


# 首页
@main.route('/', methods=['GET', 'POST'])
@main.route('/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='index_%s')
def index(page=1):
    form = SearchForm()
    pagination = Post.query.filter_by(review=True).\
        order_by(Post.id.desc()).paginate(
        page, per_page=10, error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/index.html',
        pagination=pagination,
        posts=posts,
        form=form
    )


# 搜索
@main.route('/lookup', methods=['GET', 'POST'])
def lookup():
    form = SearchForm()
    if form.validate_on_submit():
        query = form.searchName.data
        return redirect(url_for('main.search', query=query))


@main.route('/search/<string:query>', methods=['GET', 'POST'])
@main.route('/search/<string:query>/page/<int:page>', methods=['GET', 'POST'])
def search(query, page=1):
    form = SearchForm()
    pagination = Post.query.whoosh_search(query, like=True).\
        paginate(page, per_page=10, error_out=False)
    posts = pagination.items
    return render_template(
        'main/filter.html',
        type='search',
        posts=posts,
        form=form,
        query=query,
        pagination=pagination
    )


# 详细页
@main.route('/post/<string:slug>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='post_%s')
def post(slug):
    form = SearchForm()
    post = Post.query.filter_by(slug=slug).first()
    if not post:
        abort(404)
    return render_template(
        'main/post.html',
        post=post,
        form=form
    )


# 分类
@main.route('/category/<string:slug>', methods=['GET', 'POST'])
@main.route('/category/<string:slug>/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='category_%s')
def category(slug, page=1):
    form = SearchForm()
    category = Category.query.filter_by(slug=slug).first()
    if not category:
        abort(404)
    pagination = category.posts.filter_by(review=True).\
        order_by(Post.id.desc()).paginate(
        page, per_page=10, error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/filter.html',
        type='category',
        category=category,
        posts=posts,
        form=form,
        pagination=pagination
    )


# 标签
@main.route('/tag/<string:slug>', methods=['GET', 'POST'])
@main.route('/tag/<string:slug>/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='tag_%s')
def tag(slug, page=1):
    form = SearchForm()
    tag = Tag.query.filter_by(slug=slug).first()
    if not tag:
        abort(404)
    pagination = tag.posts.filter_by(review=True).\
        order_by(Post.id.desc()).paginate(
        page, per_page=10, error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/filter.html',
        type='tag',
        tag=tag,
        posts=posts,
        form=form,
        pagination=pagination
    )


# 所有标签
@main.route('/tags', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='tags')
def tags():
    form = SearchForm()
    tags = Tag.query.order_by(Tag.id.desc()).all()
    return render_template(
        'main/tags.html',
        tags=tags,
        form=form
    )


# 归档
@main.route('/archive', methods=['GET', 'POST'])
@main.route('/archive/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='archive_%s')
def archive(page=1):
    form = SearchForm()
    pagination = Post.query.filter_by(review=True).\
        order_by(Post.publish_date.desc()).paginate(
            page, per_page=10, error_out=False
        )
    posts = pagination.items
    count = Post.query.filter_by(review=True).count()
    return render_template(
        'main/archive.html',
        posts=posts,
        pagination=pagination,
        form=form,
        count=count
    )


# 链接
@main.route('/links', methods=['GET', 'POST'])
@main.route('/links/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='links_%s')
def links(page=1):
    form = SearchForm()
    pagination = Type.query.order_by(Type.order.desc()).paginate(
        page, per_page=10, error_out=False
    )
    types = pagination.items
    return render_template(
        'main/links.html',
        types=types,
        pagination=pagination,
        form=form
    )


# 作者
@main.route('/user/<string:name>', methods=['GET', 'POST'])
@main.route('/user/<string:name>/page/<int:page>', methods=['GET', 'POST'])
@cache.cached(timeout=3600, key_prefix='user_%s')
def user(name, page=1):
    form = SearchForm()
    user = User.query.filter_by(name=name).first()
    if not user:
        abort(404)
    pagination = user.posts.filter_by(review=True).\
        order_by(Post.id.desc()).paginate(
            page, per_page=10, error_out=False
        )
    posts = pagination.items
    return render_template(
        'main/filter.html',
        form=form,
        type='user',
        user=user,
        pagination=pagination,
        posts=posts
    )


# 关于
@main.route('/about')
def about():
    form = SearchForm()
    return render_template('main/about.html', form=form)


# 与我联系
@main.route('/contact')
def contact():
    form = SearchForm()
    return render_template('main/contact.html', form=form)


# rss订阅
@main.route('/feed')
def feed():
    return feeds.generate_feed().get_response()


'''
@main.route('/clear')
def clear():
    cache.clear()
'''

app/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}我爱Gvim{% endblock %}

{% block article %}
{% block anchor %}
<div class="anchor">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="/">首页</a></li>
		<li class="cur">关于我</li>
	</ul>
</div>
{% endblock %}
<div class="contact">
	关于我
</div>
{% endblock %}

app/templates/main/archive.html
{% extends 'main/base.html' %}
{% import '_page.html' as page %}

{% block title %}我爱Gvim{% endblock %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="{{ url_for('main.index') }}">首页</a></li>
		<li class="cur">归档</li>
	</ul>
</div>
{% endblock %}
{% if posts %}
	<div class="timeline">
		<span class="timeline-count"></span>
		<h4 class="tl-count">发表了<b>{{ count }}</b>篇文章</h4>
		{% for group in posts | groupby('publish_date.year') | reverse %}
			<h3 class="tl-title">{{ group.grouper }}</h3>
			{% for post in group.list %}
			<article class="tl-article">
				<div class="tl-content">
					<span class="date">{{ post.publish_date | datetimeformat('%m-%d') }}</span>
					<a href="{{ url_for('main.post', slug=post.slug) }}" class="title">{{ post.title }}</a>
				</div>
			</article>
			{% endfor %}
		{% endfor %}
	</div>
	{{ page.pagination_widget(pagination, 'main.archive') }} 
{% else %}
	<div class="archive">
		<div class="no-result">
			<p>暂时没有归档文章</p>
		</div>
	</div>
{% endif %}
{% endblock %}

app/templates/main/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
	<title>{% block title %}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="我爱Gvim">
    <meta name="keywords" content="gvim、vim、python、linux、js、javascript">
    <meta name="author" content="gvim@163.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="icon" href="{{ url_for('static', filename='main/images/favicon.ico') }}">
	<link rel="shortcut icon" href="{{ url_for('static', filename='main/images/favicon.ico') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='main/css/main.css') }}">
	{% block extra_head %}{% endblock %}
</head>
<body>
    {% block body %}
	<div class="wrap">
		<div class="wrap-container">
			<div id="container" class="clearfix">
                {% block aside %}
				<aside id="aside">
					<header role="header" class="head">
						<div id="logo"><a href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='main/images/logo.jpg')  }}" alt="我爱Gvim" class="imgRotate" /></a></div>
						<hgroup>
							<h1>我爱Gvim</h1>
							<h2>我爱Gvim，因为Gvim不仅仅是一个工具<br />更是一种信仰，一种对人生和生活的信仰</h2>
						</hgroup>
					</header>
                    {% block navigation %}
					<nav role="navigation">
						<ul class="menu">
							<li><a href="{{ url_for('main.index') }}">首页</a></li>
							<li><a href="{{ url_for('main.archive') }}">归档</a></li>
							<li><a href="{{ url_for('main.tags') }}">标签</a></li>
							<li><a href="{{ url_for('main.links') }}">链接</a></li>
						</ul>
					</nav>
                    {% endblock %}
                    {% block search %}
					<section role="search" class="search separator">
						<form action="{{ url_for('main.lookup') }}" method="post">
							{{ form.hidden_tag() }}
							<i class="fa icon-search"></i>
							{{ form.searchName(class="form_search", placeholder="请输入关键字...") }}
						</form>
						<a href="{{ url_for('main.feed') }}" class="fa icon-rss"></a>
					</section>
                    {% endblock %}
					<section>
						<div class="extra separator"></div>
					</section>
				</aside>
                {% endblock %}
                {% block content %}
				<div id="content" role="main" class="animation">
                    {% block article %}
						{% block anchor %}
						{% endblock %}
                        {% block article_header %}
                        {% endblock %}
                        {% block article_content %}
                        {% endblock %}
                    {% endblock %}
                    {% block footer %}
                        <div class="footer" role="contentinfo">
							<a href="{{ url_for('main.index') }}">首页</a>|
							<a href="{{ url_for('main.about') }}">关于</a>|
							<a href="{{ url_for('main.contact') }}">与我联系</a>|
							Generated by <a href="http://www.vim.org" target="_blank">Vim</a> &amp; <a href="http://flask.pocoo.org/" target="_blank">Flask</a>
                        </div>
                    {% endblock %}
				</div>
                {% endblock %}
			</div>
		</div>	
	</div>
    {% endblock %}
</body>
</html>

app/templates/main/contact.html
{% extends 'main/base.html' %}

{% block title %}我爱Gvim{% endblock %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="/">首页</a></li>
		<li class="cur">与我联系</li>
	</ul>
</div>
{% endblock %}
<div class="contact">
	gvim@163.com
</div>
{% endblock %}

app/templates/main/filter.html
{% extends 'main/base.html' %}
{% import '_page.html' as page %}

{% block title %}我爱Gvim{% endblock %}

{% set monthDict = {"01":"一", "02":"二", "03":"三", "04":"四", "05":"五", "06":"六", "07":"七", "08":"八", "09":"九", "10":"十", "11":"十一", "12":"十二"} %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="/">首页</a></li>
	{% if type == 'search' %}
		<li>搜索 "<b>{{ query }}</b>" 关键字</li>
	{% elif type == 'category' %}
		<li class="cur">{{ category.name }}</li>
	{% elif type == 'tag' %}
		<li><a href="{{ url_for('main.tags') }}">标签</a></li>
		<li class="cur">{{ tag.name }}</li>
	{% elif type == 'user' %}
		<li class="cur">{{ user.name }}</li>
	{% endif %}
	</ul>
</div>
{% endblock %}
{% if posts %}
	<div class="main">
	{% for post in posts %}
		<article class="article">
			<header class="header-content">
				<h1><a href="{{ url_for('main.post', slug=post.slug) }}">{{ post.title }}</a></h1>
				<div class="infoWrap">
					<span class="fa icon-admin"><a href="{{ url_for('main.user', name=post.author.name) }}">{{ post.author.name }}</a></span>
					<span class="fa icon-category"><a href="{{ url_for('main.category', slug=post.category.slug) }}"> {{ post.category }} </a></span>
					<time><span>{{ post.publish_date | datetimeformat("%d") }}</span><span>{{ monthDict[post.publish_date | datetimeformat("%m")] }}月</span></time>
					{% if post.tags %}
						<span class="fa icon-tags">
							{% for tag in post.tags %}
							<a href="{{ url_for('main.tag', slug=tag.slug) }}" style="background:{{ tag.color }}">{{ tag.name }}</a>
							{% endfor %}
						</span>
					{% endif %}
				</div>
			</header>
			<section>
				<div class="post-content">{{ post.description }}</div>
			</section>
			<a href="{{ url_for('main.post', slug=post.slug) }}" class="continue">继续阅读>></a>
		</article>
	{% endfor %}
	</div>
	{% if type == 'category' %}
		{{ page.pagination_widget(pagination, 'main.category', slug=category.slug) }}
	{% elif type == 'tag' %}
		{{ page.pagination_widget(pagination, 'main.tag', slug=tag.slug) }}
	{% elif type == 'search' %}
		{{ page.pagination_widget(pagination, 'main.search', query=query) }}
	{% elif type == 'user' %}
		{{ page.pagination_widget(pagination, 'main.user', name=user.name) }}
	{% endif %}
{% else %}
	<p>no result</p>
{% endif %}
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}
{% import '_page.html' as page %}

{% block title %}我爱Gvim{% endblock %}

{% set monthDict = {"01":"一", "02":"二", "03":"三", "04":"四", "05":"五", "06":"六", "07":"七", "08":"八", "09":"九", "10":"十", "11":"十一", "12":"十二"} %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="{{ url_for('main.index') }}">首页</a></li>
	</ul>
</div>
{% endblock %}
{% if posts %}
		<div class="main">
		{% for post in posts %}
			<article class="article">
				<header class="header-content">
					<h1><a href="{{ url_for('main.post', slug=post.slug) }}">{{ post.title }}</a></h1>
					<div class="infoWrap">
						<span class="fa icon-admin"><a href="{{ url_for('main.user', name=post.author.name) }}">{{ post.author.name }}</a></span>
						<span class="fa icon-category"><a href="{{ url_for('main.category', slug=post.category.slug) }}"> {{ post.category }} </a></span>
						<time><span>{{ post.publish_date | datetimeformat("%d") }}</span><span>{{ monthDict[post.publish_date | datetimeformat("%m")] }}月</span></time>
						{% if post.tags %}
							<span class="fa icon-tags">
								{% for tag in post.tags %}
								<a href="{{ url_for('main.tag', slug=tag.slug) }}" style="background:{{ tag.color}}">{{ tag.name }}</a>
								{% endfor %}
							</span>
						{% endif %}
					</div>
				</header>
				<section>
					<div class="post-content">{{ post.description }}</div>
				</section>
				<a href="{{ url_for('main.post', slug=post.slug) }}" class="continue">阅读全文</a>
			</article>
		{% endfor %}
		</div>
		{{ page.pagination_widget(pagination, 'main.index')}}
{% else %}
	<div class="postIndex">
		<div class="no-result">
			<p>还没有发表文章</p>
		</div>
	</div>
{% endif %}
{% endblock %}

app/templates/main/links.html
{% extends 'main/base.html' %}
{% import '_page.html' as page %}

{% block title %}链接{% endblock %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="/">首页</a></li>
		<li class="cur">链接</li>
	</ul>
</div>
{% endblock %}
<div class="links">
	{% if types %}
		<div class="link-main">
		{% for type in types %}
			<div class="link-item">
				<h2>{{ type.name }}</h2>
				{% if type.links %}
				<ul>
					{% for link in type.links %}
					<li><img src="{{ link.imgUrl }}" alt="{{ link.name }}" class="link-img"><a href="{{ link.url }}" target="_blank">{{ link.name }}</a></li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		{% endfor %}
		</div>
		{{ page.pagination_widget(pagination, 'main.links') }} 
	{% else %}
	<div class="no-result">
		<p>暂时没有链接</p>
	</div>
	{% endif %}
</div>
{% endblock %}

app/templates/main/post.html
{% extends 'main/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div id="entry-content" role="main">
	{% block article %}
	{% block anchor %}
	<div class="anchor clearfix">
		<strong>所在位置：</strong>
		<ul>
			<li><a href="/">首页</a></li>
			<li class="cur">正文</li>
		</ul>
	</div>
	{% endblock %}
		<article class="article">
			<header class="header-content">
				<h1>{{ post.title }}</h1>
				<div class="infoWrap">
						<span class="fa icon-admin"><a href="{{ url_for('main.user', name=post.author.name) }}">{{ post.author.name }}</a></span>
					<span class="fa icon-category"><a href="{{ url_for('main.category', slug=post.category.slug) }}"> {{ post.category }} </a></span>
					{% if post.tags %}
						<span class="fa icon-tags">
							{% for tag in post.tags %}
							<a href="{{ url_for('main.tag', slug=tag.slug) }}" style="background:{{ tag.color }}">{{ tag.name }}</a>
							{% endfor %}
						</span>
					{% endif %}
				</div>
			</header>
			<section>
				<div class="post-content">{{ post.content_html | safe }}</div>
			</section>
		</article>

		<div class="post_nav">
			{% if post.prev() %}
			<p>【上一篇】<a href="{{ url_for('main.post', slug=post.prev().slug) }}">{{ post.prev().title }}</a></p>
			{% else %}
				<p>【上一篇】没有上一篇文章了</p>
			{% endif %}
			{% if post.next() %}
			<p>【下一篇】<a href="{{ url_for('main.post', slug=post.next().slug) }}">{{ post.next().title }}</a></p>
			{% else %}
				<p>【下一篇】没有下一篇文章了</p>
			{% endif %}
		</div>

		<div class="relateArticle">
			<div class="relateTitle"> 相关文章 </div>
			<ul class="relateContent">
			{% if post.relativePost() %}
				{% for pArticle in  post.relativePost() %}
				<li class="fa icon-angle-left"><a href="{{ url_for('main.post', slug=pArticle.slug) }}">{{ pArticle.title }}</a></li>
				{% endfor %}
			{% else %}
				<li>没有相关文章</li>
			{% endif %}
			</ul> 
		</div> 
		
	{% endblock %}
	{% block footer %}
		{{ super() }}
	{% endblock %}
</div>
{% endblock %}

app/templates/main/search.html
<ul>
	{% for result in results %}
	<li>{{ result.title }} ---- {{ result.content }}</li>
	{% endfor %}
</ul>

app/templates/main/tags.html
{% extends 'main/base.html' %}

{% block title %}标签{% endblock %}

{% block article %}
{% block anchor %}
<div class="anchor clearfix">
	<strong>所在位置：</strong>
	<ul>
		<li><a href="{{ url_for('main.index') }}">首页</a></li>
		<li class="cur">标签</li>
	</ul>
</div>
{% endblock %}
<div class="tags">
	{% if tags %}
	<div class="tags-box">
		{% for tag in tags %}
		<a href="#{{ tag.name }}">{{ tag.name }}<sup>{{ tag.posts.count() }}</sup></a>
		{% endfor %}
	</div>
	<div class="tags-content">
		{% for tag in tags %}
		<h4><a name="{{ tag.name }}">{{ tag.name }}</a></h4>
		<ul class="tags-item">
			{% for post in tag.posts %}
			<li>{{ post.publish_date | datetimeformat() }}<a href="{{ url_for('main.post', slug=post.slug) }}">{{ post.title }}</a></li>
			{% endfor %}
		</ul>
		{% endfor %}
	</div>
	{% else %}
		<div class="no-result">
			<p>暂时没有标签</p>
		</div>
	{% endif %}
</div>
{% endblock %}